Repository SuperBuker/terraform-provider-dns-he-net, pull requests merged in 2023-09, with the labels that each got.

#42 Account id test fix
  .github/workflows/golang.yaml
  README.md
  client/client/client_test.go
  internal/datasources/account_test.go
  internal/datasources/zones_test.go
  internal/resources/AAAA_test.go
  internal/resources/A_test.go
  internal/resources/TXT_test.go
  internal/resources/ddns_key_test.go
Labels: bug

#41 Security fixes
  client/auth/README.md
  client/auth/data_store.go
  client/auth/store_utils.go
  client/auth/store_utils_test.go
  client/models/README.md
  client/models/record_SRV.go
  client/parsers/README.md
  client/parsers/records.go
  client/utils/slice.go
  internal/planmodifiers/use_state_or_default_for_unknown.go
  internal/planmodifiers/use_state_or_default_for_unknown_test.go
Labels: bug

#40 Force creation of session cookies before attempting authentication
  client/client/README.md
  client/client/client_auth.go
Labels: bug, question

#43 Go mod + sum upgrade
  .github/workflows/golang.yaml
  .github/workflows/release.yaml
  go.mod
  go.sum
Labels: maintenance

#44 Release 0.0.4
  .github/workflows/golang.yaml
  .github/workflows/release.yaml
  README.md
  client/auth/README.md
  client/auth/data_store.go
  client/auth/store_utils.go
  client/auth/store_utils_test.go
  client/client/README.md
  client/client/client_auth.go
  client/client/client_test.go
  client/models/README.md
  client/models/record_SRV.go
  client/parsers/README.md
  client/parsers/records.go
  client/utils/slice.go
  go.mod
  go.sum
  internal/datasources/account_test.go
  internal/datasources/zones_test.go
  internal/planmodifiers/README.md
  internal/planmodifiers/use_state_or_default_for_unknown.go
  internal/planmodifiers/use_state_or_default_for_unknown_test.go
  internal/resources/AAAA_test.go
  internal/resources/A_test.go
  internal/resources/TXT_test.go
  internal/resources/ddns_key_test.go
Labels: bug, enhancement
